### ISSUE TITLE
Adding relationships through submission doesn't update view automatically

### ISSUE THREAD

**Issue by Atmire-Kristof** [DSpace/dspace-angular#1671]
**Describe the bug**
When adding (or removing) a relationship to an item in submission, the view (list displayed under the field's input) doesn't update automatically. The relationship is correctly added/removed to/from the item, but isn't visible until a page reload.

**To Reproduce**
* Start a submission for an item in a collection that contains a relationship input (as of writing this, the "People 2" collection contains a relationship input for "Publications" on [Demo](https://demo7.dspace.org/))
* Click the lookup for that field and select an item
* The item isn't visible under the input
![Screenshot 2022-06-01 at 15 58 08](https://user-images.githubusercontent.com/34308852/171423923-00cc6220-8d8a-4f41-ab1a-b0b55078e35a.png)
* Reload the page
* The item is visible under the input
![Screenshot 2022-06-01 at 15 58 33](https://user-images.githubusercontent.com/34308852/171423949-8b9de9f2-0c2c-42af-89ca-138164335191.png)
* Click the delete button next to the related item
* Nothing seems to happen (although a request is sent to the REST API)
* Reload the page
* The related item under the input is gone

**Expected behavior**
The relationships should display under the inputs after adding/removing them without requiring a page reload.

**Comment by tdonohue** [comment]
@artlowel and @Atmire-Kristof : any chance this is something simple?  Just curious if there's any way we can get this fixed in 7.3, as it seems like an annoying issue.  If you feel that the Atmire team could take this on, let me know...would be glad to prioritize this for immediate fixing.

**Comment by Atmire-Kristof** [comment]
@tdonohue really hard for me to tell if this is an easy fix or not. I had a brief look at it and didn't find anything that could be related just yet.

**Comment by ybnd** [comment]
Running into this issue again, here's some more info
* When the field is repeateble, the "Add more" button is disabled along with the input itself
* Looks like this bug _doesn't_ occur for fields that define a `<linked-metadata-field>`

**Comment by ybnd** [comment]
@tdonohue Atmire would like to claim this issue.

@samuelcambien found out that the underlying problem is backend-related: the reloading of the Relationships depends on the output of the `DescribeStep` -- if we include virtual MDVs there, the form updates as expected.

This ended up being pretty tough to debug, we spent about **16h** already.
I estimate it would take another **4h** to finish up, mainly to address the related bug with repeatable fields I mentioned above.
