### ISSUE TITLE
Curation Tasks (Administrative function)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#285]
This is a placeholder ticket for an eventual implementation of the Curation Tasks interface for the Angular UI (e.g. XMLUI version at http://demo.dspace.org/xmlui/admin/curate).

During the [DevMtg on Aug 8](https://wiki.duraspace.org/display/DSPACE/DevMtg+2018-08-08), those in attendance discussed/brainstormed improvements to Curation Tasks based on the brainstorms at https://wiki.duraspace.org/display/~terrywbrady/Curation+System+Needs

Out of those discussions came a few nearterm improvements that could be made in DSpace 7, primarily:

* Find a way to "stream" task output to the Angular UI, so that what is displayed in DSpace 7 UI looks very similar to what is displayed via STDOUT / commandline.  (This would be a difference in behavior from DSpace 6, where the output of a task is just the final status & the *last* item updated by the task)
* Likely we'll want curation task output (which is text-based) to remain unchanged for now (to avoid major curation task refactoring). But, we'll want to ensure the REST API endpoint is structured in a way that Angular can subscribe to it (for that "stream" of output).

Other tickets/discussions related to this topic include:
* https://github.com/DSpace/Rest7Contract/pull/17

**Comment by heathergreerklein** [comment]
Closing; addressed in this PR per Atmire: https://github.com/DSpace/DSpace/pull/2820

**Comment by artlowel** [comment]
@heathergreerklein In a meeting early this year we discussed the scripts & processes admin UI designs and came to the conclusion that it was fine for someone familiar with cli scripts, but not user friendly enough for the average user. 

So things that had a UI in dspace 6 that will now be handled by scripts & processes in the backend will still get a UI in dspace 7, but that UI will use the scripts & process rest endpoints and in some cases the process overview page.

We're already working on that UI for curation tasks, expect a PR next week.
